# Generated by Django 4.0.6 on 2022-08-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200)),
                ('name_ar', models.CharField(max_length=200)),
                ('uid', models.IntegerField(unique=True)),
                ('mobile', models.CharField(max_length=14, unique=True)),
                ('phone', models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
