# Generated by Django 4.0.6 on 2022-08-20 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_pharmacycustomer_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacycustomer',
            old_name='name_en',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='pharmacycustomer',
            name='name_ar',
        ),
    ]
